'use client';
import {useEffect,useMemo,useState} from 'react';
import MapView from './MapView';
type Status='Open'|'Opening soon'|'Closed'|'Verify';
type Tier='Major'|'Global label'|'Iconic';
type Race={city:string;country:string;code:string;region:string;name:string;date:string;event?:string;registration:string;status:Status;terrain:string;tier:Tier;link:string;featured?:boolean;lat?:number;lon?:number;distances?:string[]};
const r=(city:string,country:string,code:string,region:string,name:string,date:string,registration:string,status:Status,terrain:string,tier:Tier,link:string,event?:string,featured?:boolean):Race=>({city,country,code,region,name,date,registration,status,terrain,tier,link,event,featured});
const races:Race[]=[
r('Berlin','Germany','DE','Europe','BMW Berlin Marathon','2026-09-27','Entry closed','Closed','Fast & flat','Major','https://www.bmw-berlin-marathon.com/',undefined,true),
r('Lisbon','Portugal','PT','Europe','EDP Lisbon Marathon','2026-10-10','Check current availability','Verify','Coastal','Global label','https://maratonaclubedeportugal.com/en/'),
r('Chicago','United States','US','Americas','Bank of America Chicago Marathon','2026-10-11','Entry closed','Closed','Fast & flat','Major','https://www.chicagomarathon.com/'),
r('Montréal','Canada','CA','Americas','Marathon Beneva de Montréal','2026-10-11','Check current availability','Verify','Rolling','Global label','https://mtlmarathon.com/en/'),
r('Beijing','China','CN','Asia','Beijing Marathon','2026-10-18','Entry / ballot closed','Closed','City course','Global label','https://www.beijing-marathon.com/'),
r('Amsterdam','Netherlands','NL','Europe','TCS Amsterdam Marathon','2026-10-18','Check current availability','Verify','Fast & flat','Global label','https://www.tcsamsterdammarathon.eu/'),
r('Toronto','Canada','CA','Americas','TCS Toronto Waterfront Marathon','2026-10-18','Check current availability','Verify','Fast & flat','Global label','https://www.torontowaterfrontmarathon.com/'),
r('Dublin','Ireland','IE','Europe','Irish Life Dublin Marathon','2026-10-25','Entry closed','Closed','Rolling','Global label','https://irishlifedublinmarathon.ie/'),
r('Frankfurt','Germany','DE','Europe','Mainova Frankfurt Marathon','2026-10-25','Check current availability','Verify','Fast','Global label','https://www.frankfurt-marathon.com/en/'),
r('Venice','Italy','IT','Europe','Venicemarathon','2026-10-25','Check current availability','Verify','Flat & bridges','Global label','https://www.venicemarathon.it/en/'),
r('New York','United States','US','Americas','TCS New York City Marathon','2026-11-01','Entry closed','Closed','Hilly','Major','https://www.nyrr.org/tcsnycmarathon'),
r('Istanbul','Türkiye','TR','Europe','Türkiye İş Bankası Istanbul Marathon','2026-11-01','Check current availability','Verify','Intercontinental','Global label','https://maraton.istanbul/'),
r('Athens','Greece','GR','Europe','Athens Marathon — The Authentic','2026-11-08','Check current availability','Verify','Historic & hilly','Iconic','https://www.athensauthenticmarathon.gr/'),
r('Porto','Portugal','PT','Europe','EDP Porto Marathon','2026-11-08','Check current availability','Verify','Riverside','Global label','https://www.maratonadoporto.com/en/'),
r('Valencia','Spain','ES','Europe','Valencia Marathon Trinidad Alfonso','2026-12-06','Entry closed / waitlist','Closed','Fast & flat','Global label','https://www.valenciaciudaddelrunning.com/en/marathon/'),
r('Honolulu','United States','US','Americas','Honolulu Marathon','2026-12-13','Registration open','Open','Tropical & rolling','Iconic','https://www.honolulumarathon.org/'),
r('Houston','United States','US','Americas','Chevron Houston Marathon','2027-01-17','Check current availability','Verify','Fast & flat','Global label','https://www.chevronhoustonmarathon.com/'),
r('Mumbai','India','IN','Asia','Tata Mumbai Marathon','2027-01-17','Expected Aug–Nov 2026','Opening soon','Coastal city','Global label','https://tatamumbaimarathon.procam.in/'),
r('Dubai','United Arab Emirates','AE','Asia','Dubai Marathon','2027-01-17','Registration open','Open','Fast & flat','Global label','https://www.dubaimarathon.org/',undefined),
r('Tokyo','Japan','JP','Asia','Tokyo Marathon','2027-03-07','Closed Aug 28, 2026','Closed','Fast & flat','Major','https://www.marathon.tokyo/en/'),
r('Los Angeles','United States','US','Americas','Los Angeles Marathon','2027-03-21','Registration open','Open','Point-to-point','Iconic','https://www.mccourtfoundation.org/pages/la-marathon'),
r('Seoul','South Korea','KR','Asia','Seoul Marathon','2027-03-21','Overseas registration open','Open','Fast city course','Global label','https://en.seoul-marathon.com/83'),
r('Paris','France','FR','Europe','Schneider Electric Marathon de Paris','','Check official entry portal','Verify','City landmarks','Global label','https://www.schneiderelectricparismarathon.com/en','April 2027 · TBA'),
r('Rotterdam','Netherlands','NL','Europe','NN Marathon Rotterdam','','Dates not announced','Opening soon','Fast & flat','Global label','https://www.nnmarathonrotterdam.org/','April 2027 · TBA'),
r('Boston','United States','US','Americas','Boston Marathon','2027-04-19','Sep 14–18, 2026','Opening soon','Historic & hilly','Major','https://www.baa.org/races/boston-marathon'),
r('London','United Kingdom','GB','Europe','TCS London Marathon','2027-04-24','Ballot closed May 1, 2026','Closed','Flat','Major','https://www.londonmarathonevents.co.uk/london-marathon','Apr 24–25, 2027'),
r('Madrid','Spain','ES','Europe','Rock ’n’ Roll Madrid Marathon','','Dates not announced','Opening soon','Hilly','Global label','https://www.runrocknroll.com/madrid','April 2027 · TBA'),
r('Vienna','Austria','AT','Europe','Vienna City Marathon','2027-04-18','Entry closed','Closed','Fast city course','Global label','https://www.vienna-marathon.com/index.html?go=events&lang=en'),
r('Prague','Czechia','CZ','Europe','Vodafone Prague Marathon','2027-05-02','Registration open','Open','Mostly flat','Global label','https://www.runczech.com/en/events/vodafone-prague-marathon-2027/races/vodafone-prague-marathon'),
r('Copenhagen','Denmark','DK','Europe','Copenhagen Marathon','2027-05-09','Lottery closed','Closed','Flat','Global label','https://copenhagenmarathon.dk/en/'),
r('Cape Town','South Africa','ZA','Africa','Sanlam Cape Town Marathon','','Dates not announced','Opening soon','Scenic city','Global label','https://capetownmarathon.com/','May 2027 · TBA'),
r('Ottawa','Canada','CA','Americas','Tartan Ottawa International Marathon','','Dates not announced','Opening soon','Scenic & rolling','Global label','https://www.runottawa.ca/','May 2027 · TBA'),
r('Stockholm','Sweden','SE','Europe','adidas Stockholm Marathon','2027-05-29','Registration available','Open','Urban & waterfront','Global label','https://stockholmmarathon.se/eng/eng-lopare/'),
r('Rio de Janeiro','Brazil','BR','Americas','Maratona do Rio','2027-05-30','42K registration open','Open','Coastal','Global label','https://maratonadorio.com.br/en','May 27–30, 2027'),
r('Gold Coast','Australia','AU','Oceania','ASICS Gold Coast Marathon','','Dates not announced','Opening soon','Fast & coastal','Global label','https://goldcoastmarathon.com.au/','July 2027 · TBA'),
r('Sydney','Australia','AU','Oceania','TCS Sydney Marathon','','Dates not announced','Opening soon','Scenic & rolling','Major','https://sydneymarathon.com/','August 2027 · TBA'),
r('Buenos Aires','Argentina','AR','Americas','Maratón de Buenos Aires','2026-09-20','Check current availability','Verify','Fast & flat','Global label','https://www.maratondebuenosaires.com/'),
r('Casablanca','Morocco','MA','Africa','Casablanca Marathon','2026-10-25','Check current availability','Verify','Coastal city','Global label','https://www.casablanca-marathon.com/'),
r('Marrakech','Morocco','MA','Africa','Marrakesh International Marathon','','Dates not announced','Opening soon','Flat & scenic','Global label','https://www.marathon-marrakech.com/','January 2027 · TBA'),
r('São Paulo','Brazil','BR','Americas','Maratona Internacional de São Paulo','','Dates not announced','Opening soon','Urban & rolling','Global label','https://www.yescom.com.br/maratonasp/','April 2027 · TBA'),
r('Santiago','Chile','CL','Americas','Maratón de Santiago','','Dates not announced','Opening soon','Urban & rolling','Iconic','https://maratondesantiago.com/','April 2027 · TBA'),
r('Lima','Peru','PE','Americas','Lima Marathon','','Dates not announced','Opening soon','Coastal & flat','Global label','https://www.limamarathon.com/','May 2027 · TBA'),
r('Rabat','Morocco','MA','Africa','Rabat International Marathon','','Dates not announced','Opening soon','City & coastal','Global label','https://www.marathonderabat.com/','May 2027 · TBA'),
r('Durban','South Africa','ZA','Africa','Durban International Marathon','','Dates not announced','Opening soon','Coastal','Global label','https://durbanmarathon.co.za/','May 2027 · TBA'),
r('Porto Alegre','Brazil','BR','Americas','New Balance 42K Porto Alegre','','Dates not announced','Opening soon','Fast city course','Global label','https://www.42kpoa.com.br/','July 2027 · TBA'),
r('Nairobi','Kenya','KE','Africa','Standard Chartered Nairobi Marathon','','Dates not announced','Opening soon','High altitude','Iconic','https://www.nairobimarathon.com/','October 2027 · TBA'),
];
const fmt=(date:string)=>new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric'}).format(new Date(`${date}T12:00:00`));
const eventDate=(race:Race)=>race.event||fmt(race.date);
const weekday=(race:Race)=>race.date?new Intl.DateTimeFormat('en-US',{weekday:'long'}).format(new Date(`${race.date}T12:00:00`)):'Official date pending';
const slug=(s:string)=>s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
const coords:Record<string,[number,number]>={Berlin:[52.5,13.4],Lisbon:[38.7,-9.1],Chicago:[41.9,-87.6],'Montréal':[45.5,-73.6],Beijing:[39.9,116.4],Amsterdam:[52.4,4.9],Toronto:[43.7,-79.4],Dublin:[53.3,-6.3],Frankfurt:[50.1,8.7],Venice:[45.4,12.3],'New York':[40.7,-74],Istanbul:[41,29],Athens:[38,23.7],Porto:[41.2,-8.6],Valencia:[39.5,-.4],Honolulu:[21.3,-157.9],Houston:[29.8,-95.4],Mumbai:[19.1,72.9],Dubai:[25.2,55.3],Tokyo:[35.7,139.7],'Los Angeles':[34.1,-118.2],Seoul:[37.6,127],Paris:[48.9,2.4],Rotterdam:[51.9,4.5],Boston:[42.4,-71.1],London:[51.5,-.1],Madrid:[40.4,-3.7],Vienna:[48.2,16.4],Prague:[50.1,14.4],Copenhagen:[55.7,12.6],'Cape Town':[-33.9,18.4],Ottawa:[45.4,-75.7],Stockholm:[59.3,18.1],'Rio de Janeiro':[-22.9,-43.2],'Gold Coast':[-28,153.4],Sydney:[-33.9,151.2],'Buenos Aires':[-34.6,-58.4],Casablanca:[33.6,-7.6],Marrakech:[31.6,-8],'São Paulo':[-23.6,-46.6],Santiago:[-33.5,-70.7],Lima:[-12,-77],Rabat:[34,-6.8],Durban:[-29.9,31],'Porto Alegre':[-30,-51.2],Nairobi:[-1.3,36.8]};
const multiDistance=new Set(['Lisbon','Montréal','Toronto','Frankfurt','Venice','Istanbul','Athens','Porto','Honolulu','Houston','Mumbai','Dubai','Los Angeles','Madrid','Prague','Copenhagen','Cape Town','Ottawa','Rio de Janeiro','Gold Coast','Sydney','Buenos Aires','Casablanca','Marrakech','São Paulo','Santiago','Lima','Rabat','Durban','Porto Alegre','Nairobi']);
const distances=(race:Race)=>race.distances?.length?race.distances:race.city==='Chicago'||race.city==='New York'||race.city==='Boston'?['Marathon','5K']:multiDistance.has(race.city)?['Marathon','Half marathon','10K','5K']:['Marathon'];
export default function Home(){
 const[catalog,setCatalog]=useState<Race[]>(races);const[lastUpdated,setLastUpdated]=useState('October 5, 2026');
 const[query,setQuery]=useState('');const[region,setRegion]=useState('All regions');const[openOnly,setOpenOnly]=useState(false);const[distance,setDistance]=useState('All distances');const[sort,setSort]=useState('event');const[view,setView]=useState<'list'|'map'>('list');
 useEffect(()=>{let active=true;fetch('/api/races',{cache:'no-store'}).then(response=>response.ok?response.json():Promise.reject()).then(data=>{if(active&&Array.isArray(data.races)&&data.races.length){setCatalog(data.races);if(data.updatedAt)setLastUpdated(new Intl.DateTimeFormat('en-US',{month:'long',day:'numeric',year:'numeric'}).format(new Date(data.updatedAt)))}}).catch(()=>{});return()=>{active=false}},[]);
 const filtered=useMemo(()=>catalog.filter(x=>`${x.city} ${x.country} ${x.name}`.toLowerCase().includes(query.toLowerCase())&&(region==='All regions'||x.region===region)&&(!openOnly||x.status==='Open')&&(distance==='All distances'||distances(x).includes(distance))).sort((a,b)=>{if(sort==='registration'){const rank=(x:Race)=>x.status==='Open'?0:x.status==='Opening soon'?1:x.status==='Verify'?2:3;return rank(a)-rank(b)}return(a.date||'9999').localeCompare(b.date||'9999')}),[catalog,query,region,openOnly,distance,sort]);
 const featured=catalog.find(x=>x.featured)||catalog[0];
 return <main><nav className="nav shell"><a className="brand" href="#top" aria-label="Pace Atlas home"><span className="brand-mark">PA</span><span>Pace Atlas</span></a><div className="nav-links"><a href="#directory">Explore races</a><a href="#about">About</a></div><a className="save-link" href="#directory">Find your race <span>↗</span></a></nav>
 <section className="hero shell" id="top"><div className="eyebrow"><span>●</span> Live race calendar</div><h1>Your next finish line<br/>starts with a <em>city.</em></h1><p className="hero-copy">The world’s major, globally labelled, and truly iconic destination marathons—without the noise of every local race.</p><div className="search-wrap"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by city, country, or race" aria-label="Search races"/><a href="#directory">Explore <span>→</span></a></div><div className="quick-stats"><div><strong>{catalog.length}</strong><span>notable races</span></div><div><strong>{new Set(catalog.map(x=>x.country)).size}</strong><span>countries</span></div><div><strong>{catalog.filter(x=>x.tier==='Major').length}</strong><span>world majors</span></div></div></section>
 <section className="feature-band"><div className="shell feature-card"><div><div className="feature-label">Featured race · Abbott World Major</div><h2>{featured.city}<br/><span>Marathon</span></h2></div><div className="feature-info"><p>One of the world’s fastest courses and a defining stop on the international marathon calendar.</p><div className="date-row"><div><span>Race day</span><strong>{eventDate(featured)}</strong></div><div><span>Registration</span><strong>{featured.registration}</strong></div></div><a href={featured.link} target="_blank" rel="noreferrer">View official race site <span>↗</span></a></div><div className="route-art" aria-hidden="true"><span className="route-dot start">START</span><div className="route-line">⌁</div><span className="route-dot finish">FINISH</span><b>42.195</b><small>KILOMETRES</small></div></div></section>
 <section className="directory shell" id="directory"><div className="section-head"><div><span className="kicker">THE GLOBAL SHORTLIST</span><h2>Find your next <em>race</em></h2></div><p>Explore event-weekend distances, compare key dates, or browse geographically. Always confirm final pricing and policies with the organizer.</p></div>
 <div className="tool-row"><div className="view-switch"><button className={view==='list'?'active':''} onClick={()=>setView('list')}>☷ List</button><button className={view==='map'?'active':''} onClick={()=>setView('map')}>⌖ Map</button></div><div className="select-filters"><label>Distance <select value={distance} onChange={e=>setDistance(e.target.value)}>{['All distances','Marathon','Half marathon','10K','5K'].map(x=><option key={x}>{x}</option>)}</select></label><label>Sort by <select value={sort} onChange={e=>setSort(e.target.value)}><option value="event">Event date</option><option value="registration">Registration status</option></select></label></div></div>
 <div className="filters"><div className="region-tabs" aria-label="Filter by region">{['All regions','Americas','Europe','Asia','Africa','Oceania'].map(x=><button className={region===x?'active':''} onClick={()=>setRegion(x)} key={x}>{x}</button>)}</div><label className="toggle"><input type="checkbox" checked={openOnly} onChange={e=>setOpenOnly(e.target.checked)}/><span/> Open registration only</label></div>
 {view==='map'?<div className="map-shell"><MapView races={filtered.flatMap(x=>{const point=x.lat!==undefined&&x.lon!==undefined?[x.lat,x.lon]:coords[x.city];if(!point)return[];const[lat,lon]=point;return[{city:x.city,country:x.country,name:x.name,date:eventDate(x),registration:x.registration,status:x.status,lat,lon,href:`/race/${slug(x.city)}`}]} )}/><div className="map-note">{filtered.length} events shown · Zoom, pan, or select a marker</div></div>:
 <div className="race-table"><div className="table-head"><span>City & race</span><span>Event date</span><span>Registration</span><span>Status</span><span/></div>{filtered.map((x,i)=><article className="race-row" key={x.name}><div className="race-name"><span className="num">{String(i+1).padStart(2,'0')}</span><span className="country-code">{x.code}</span><div><h3>{x.city} <small className={`tier ${x.tier==='Major'?'major':''}`}>{x.tier}</small></h3><p>{x.name} · {x.terrain} · {distances(x).join(' / ')}</p></div></div><div className="cell" data-label="Event date"><strong>{eventDate(x)}</strong><span>{weekday(x)}</span></div><div className="cell" data-label="Registration"><strong>{x.registration}</strong><a href={x.link} target="_blank" rel="noreferrer">Official source</a></div><div><span className={`status ${x.status.toLowerCase().replace(' ','-')}`}><i/>{x.status}</span></div><a className="race-link" href={`/race/${slug(x.city)}`} aria-label={`View ${x.name} details`}>→</a></article>)}{filtered.length===0&&<div className="empty"><strong>No races found.</strong><span>Try a different distance or broaden your filters.</span></div>}</div>}
 </section>
 <footer id="about"><div className="shell footer-inner"><div><a className="brand light" href="#top"><span className="brand-mark">PA</span><span>Pace Atlas</span></a><p>A global shortlist for runners chasing cities and finish lines.</p></div><div><span>Database updated</span><strong>{lastUpdated}</strong></div><a href="#top">Back to top ↑</a></div></footer></main>;
}
