import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import cityCredits from '../../../public/images/cities/credits.json';

type Detail={city:string;country:string;name:string;date:string;registration:string;terrain:string;official:string;distances:string;route:string};
const rows=[
'berlin|Berlin|Germany|BMW Berlin Marathon|Sep 27, 2026|Entry closed|Fast & flat|https://www.bmw-berlin-marathon.com/|Marathon|A famously quick point-to-point course through central Berlin, finishing through the Brandenburg Gate.',
'lisbon|Lisbon|Portugal|EDP Lisbon Marathon|Oct 10, 2026|Check availability|Coastal|https://maratonaclubedeportugal.com/en/|Marathon · Half · 10K · 5K|A scenic coastal route into Lisbon with long open stretches and an urban finish.',
'chicago|Chicago|United States|Bank of America Chicago Marathon|Oct 11, 2026|Entry closed|Fast & flat|https://www.chicagomarathon.com/|Marathon · 5K|A flat loop through 29 neighbourhoods with dense crowd support and few meaningful climbs.',
'montreal|Montréal|Canada|Marathon Beneva de Montréal|Oct 11, 2026|Check availability|Rolling|https://mtlmarathon.com/en/|Marathon · Half · 10K · 5K|An urban tour linking Montréal neighbourhoods with a gently rolling profile.',
'beijing|Beijing|China|Beijing Marathon|Oct 18, 2026|Entry / ballot closed|City course|https://www.beijing-marathon.com/|Marathon|A landmark-rich city course connecting central Beijing with the Olympic precinct.',
'amsterdam|Amsterdam|Netherlands|TCS Amsterdam Marathon|Oct 18, 2026|Check availability|Fast & flat|https://www.tcsamsterdammarathon.eu/|Marathon|A flat route beginning and ending in the Olympic Stadium, with an Amstel River section.',
'toronto|Toronto|Canada|TCS Toronto Waterfront Marathon|Oct 18, 2026|Check availability|Fast & flat|https://www.torontowaterfrontmarathon.com/|Marathon · Half · 10K · 5K|A fast downtown-and-waterfront course built for personal bests.',
'dublin|Dublin|Ireland|Irish Life Dublin Marathon|Oct 25, 2026|Entry closed|Rolling|https://irishlifedublinmarathon.ie/|Marathon|A single-lap city course with rolling sections and famously vocal support.',
'frankfurt|Frankfurt|Germany|Mainova Frankfurt Marathon|Oct 25, 2026|Check availability|Fast|https://www.frankfurt-marathon.com/en/|Marathon · Half · 10K · 5K|A quick urban course known for its indoor red-carpet finish at Festhalle.',
'venice|Venice|Italy|Venicemarathon|Oct 25, 2026|Check availability|Flat & bridges|https://www.venicemarathon.it/en/|Marathon · Half · 10K · 5K|Mostly flat from the mainland to Venice, with bridges adding rhythm late in the race.',
'new-york|New York|United States|TCS New York City Marathon|Nov 1, 2026|Entry closed|Hilly|https://www.nyrr.org/tcsnycmarathon|Marathon · 5K|A five-borough point-to-point journey with bridges, rolling roads, and a Central Park finish.',
'istanbul|Istanbul|Türkiye|Istanbul Marathon|Nov 1, 2026|Check availability|Intercontinental|https://maraton.istanbul/|Marathon · Half · 10K · 5K|The only marathon spanning two continents, crossing the Bosphorus into historic Istanbul.',
'athens|Athens|Greece|Athens Marathon — The Authentic|Nov 8, 2026|Check availability|Historic & hilly|https://www.athensauthenticmarathon.gr/|Marathon · Half · 10K · 5K|The historic route from Marathon to Athens includes a long demanding middle climb.',
'porto|Porto|Portugal|EDP Porto Marathon|Nov 8, 2026|Check availability|Riverside|https://www.maratonadoporto.com/en/|Marathon · Half · 10K · 5K|A river-and-Atlantic course showcasing Porto and neighbouring waterfronts.',
'valencia|Valencia|Spain|Valencia Marathon Trinidad Alfonso|Dec 6, 2026|Entry closed / waitlist|Fast & flat|https://www.valenciaciudaddelrunning.com/en/marathon/|Marathon|One of the fastest courses in the world, with broad roads and a spectacular water finish.',
'honolulu|Honolulu|United States|Honolulu Marathon|Dec 13, 2026|Registration open|Tropical & rolling|https://www.honolulumarathon.org/|Marathon · Half · 10K · 5K|A tropical route past Waikiki and Diamond Head with no official time limit.',
'houston|Houston|United States|Chevron Houston Marathon|Jan 17, 2027|Check availability|Fast & flat|https://www.chevronhoustonmarathon.com/|Marathon · Half · 10K · 5K|A fast urban loop with broad roads, light elevation, and strong elite fields.',
'mumbai|Mumbai|India|Tata Mumbai Marathon|Jan 17, 2027|Expected Aug–Nov 2026|Coastal city|https://tatamumbaimarathon.procam.in/|Marathon · Half · 10K · 5K|A humid coastal city course passing major Mumbai landmarks and the sea link.',
'dubai|Dubai|United Arab Emirates|Dubai Marathon|Jan 17, 2027|Registration open|Fast & flat|https://www.dubaimarathon.org/|Marathon · 10K · 4K|A very flat road course designed for speed along Dubai’s wide boulevards.',
'tokyo|Tokyo|Japan|Tokyo Marathon|Mar 7, 2027|Closed Aug 28, 2026|Fast & flat|https://www.marathon.tokyo/en/|Marathon|A point-to-point tour of central Tokyo with small undulations and a fast finish.',
'los-angeles|Los Angeles|United States|Los Angeles Marathon|Mar 21, 2027|Registration open|Point-to-point|https://www.mccourtfoundation.org/pages/la-marathon|Marathon · Half · 10K · 5K|A landmark-heavy point-to-point course with rolling sections across Los Angeles.',
'seoul|Seoul|South Korea|Seoul Marathon|Mar 21, 2027|Overseas registration open|Fast city course|https://en.seoul-marathon.com/83|Marathon · 10K|A quick urban course connecting historic central Seoul with the Olympic Stadium area.',
'paris|Paris|France|Schneider Electric Marathon de Paris|April 2027 · TBA|Check official portal|City landmarks|https://www.schneiderelectricparismarathon.com/en|Marathon|A grand tour from the Champs-Élysées past central landmarks and wooded park sections.',
'rotterdam|Rotterdam|Netherlands|NN Marathon Rotterdam|April 2027 · TBA|Dates not announced|Fast & flat|https://www.nnmarathonrotterdam.org/|Marathon|A fast city loop known for dense crowds, bridges, and record-friendly racing.',
'boston|Boston|United States|Boston Marathon|Apr 19, 2027|Sep 14–18, 2026|Historic & hilly|https://www.baa.org/races/boston-marathon|Marathon · 5K|The historic point-to-point course from Hopkinton features Newton’s hills and a net descent.',
'london|London|United Kingdom|TCS London Marathon|Apr 24–25, 2027|Ballot closed May 1, 2026|Flat|https://www.londonmarathonevents.co.uk/london-marathon|Marathon|A mostly flat route from Greenwich along the Thames to the Mall.',
'madrid|Madrid|Spain|Rock ’n’ Roll Madrid Marathon|April 2027 · TBA|Dates not announced|Hilly|https://www.runrocknroll.com/madrid|Marathon · Half · 10K · 5K|A lively but challenging city course with sustained elevation changes.',
'vienna|Vienna|Austria|Vienna City Marathon|Apr 18, 2027|Entry closed|Fast city course|https://www.vienna-marathon.com/index.html?go=events&lang=en|Marathon · Half · 10K · 5K|A broad-road city tour passing the Danube, Prater, and central Vienna landmarks.',
'prague|Prague|Czechia|Vodafone Prague Marathon|May 2, 2027|Registration open|Mostly flat|https://www.runczech.com/en/events/vodafone-prague-marathon-2027/races/vodafone-prague-marathon|Marathon|A cobble-accented historic route crossing the Vltava and central Prague.',
'copenhagen|Copenhagen|Denmark|Copenhagen Marathon|May 9, 2027|Lottery closed|Flat|https://copenhagenmarathon.dk/en/|Marathon|A flat multi-neighbourhood course with energetic Scandinavian crowd support.',
'cape-town|Cape Town|South Africa|Sanlam Cape Town Marathon|May 2027 · TBA|Dates not announced|Scenic city|https://capetownmarathon.com/|Marathon · Half · 10K · 5K|A scenic city course framed by Table Mountain with some rolling sections.',
'ottawa|Ottawa|Canada|Tartan Ottawa International Marathon|May 2027 · TBA|Dates not announced|Scenic & rolling|https://www.runottawa.ca/|Marathon · Half · 10K · 5K|A scenic capital-region route crossing waterways and passing national landmarks.',
'stockholm|Stockholm|Sweden|adidas Stockholm Marathon|May 29, 2027|Registration available|Urban & waterfront|https://stockholmmarathon.se/eng/eng-lopare/|Marathon|A waterfront-heavy city course across Stockholm’s islands with gentle rolling terrain.',
'rio-de-janeiro|Rio de Janeiro|Brazil|Maratona do Rio|May 27–30, 2027|42K registration open|Coastal|https://maratonadorio.com.br/en|Marathon · Half · 10K · 5K|A scenic coastal route with long ocean views and warm-weather racing.',
'gold-coast|Gold Coast|Australia|ASICS Gold Coast Marathon|July 2027 · TBA|Dates not announced|Fast & coastal|https://goldcoastmarathon.com.au/|Marathon · Half · 10K · 5K|A flat out-and-back coastal course known for mild conditions and fast times.',
'sydney|Sydney|Australia|TCS Sydney Marathon|August 2027 · TBA|Dates not announced|Scenic & rolling|https://sydneymarathon.com/|Marathon · 10K|A landmark course crossing the Harbour Bridge and finishing at the Opera House.',
'buenos-aires|Buenos Aires|Argentina|Maratón de Buenos Aires|Sep 20, 2026|Check current availability|Fast & flat|https://www.maratondebuenosaires.com/|Marathon · Half · 10K · 5K|A broad, fast city course through the Argentine capital and its landmark neighbourhoods.',
'casablanca|Casablanca|Morocco|Casablanca Marathon|Oct 25, 2026|Check current availability|Coastal city|https://www.casablanca-marathon.com/|Marathon · Half · 10K · 5K|A coastal urban route through Morocco’s largest city with long runnable sections.',
'marrakech|Marrakech|Morocco|Marrakesh International Marathon|January 2027 · TBA|Dates not announced|Flat & scenic|https://www.marathon-marrakech.com/|Marathon · Half · 10K · 5K|A largely flat circuit framed by palms, the Atlas Mountains, and Marrakech’s historic walls.',
'sao-paulo|São Paulo|Brazil|Maratona Internacional de São Paulo|April 2027 · TBA|Dates not announced|Urban & rolling|https://www.yescom.com.br/maratonasp/|Marathon · Half · 10K · 5K|A major-city course through São Paulo with rolling sections and broad avenues.',
'santiago|Santiago|Chile|Maratón de Santiago|April 2027 · TBA|Dates not announced|Urban & rolling|https://maratondesantiago.com/|Marathon · Half · 10K · 5K|A high-energy capital route with Andean views and a gently rolling city profile.',
'lima|Lima|Peru|Lima Marathon|May 2027 · TBA|Dates not announced|Coastal & flat|https://www.limamarathon.com/|Marathon · Half · 10K · 5K|A mostly flat metropolitan course with sections near Lima’s Pacific coastline.',
'rabat|Rabat|Morocco|Rabat International Marathon|May 2027 · TBA|Dates not announced|City & coastal|https://www.marathonderabat.com/|Marathon · Half · 10K · 5K|A capital-city route combining boulevards, historic districts, and Atlantic air.',
'durban|Durban|South Africa|Durban International Marathon|May 2027 · TBA|Dates not announced|Coastal|https://durbanmarathon.co.za/|Marathon · Half · 10K · 5K|A warm-weather coastal course along Durban’s broad roads and Indian Ocean waterfront.',
'porto-alegre|Porto Alegre|Brazil|New Balance 42K Porto Alegre|July 2027 · TBA|Dates not announced|Fast city course|https://www.42kpoa.com.br/|Marathon · Half · 10K · 5K|A quick southern Brazilian city course known for strong local participation.',
'nairobi|Nairobi|Kenya|Standard Chartered Nairobi Marathon|October 2027 · TBA|Dates not announced|High altitude|https://www.nairobimarathon.com/|Marathon · Half · 10K · 5K|A high-altitude capital race with rolling roads and a large East African field.',
];
const details=Object.fromEntries(rows.map(row=>{const[s,city,country,name,date,registration,terrain,official,distances,route]=row.split('|');return[s,{city,country,name,date,registration,terrain,official,distances,route}] as const})) as Record<string,Detail>;
const routeEvidence:Record<string,{elevation:string;note:string;source:string;label:string}>={
 toronto:{elevation:'Estimated cumulative rise: 138 m',note:'The published course runs through downtown and along the waterfront. The organizer notes that the course remains subject to change.',source:'https://www.torontowaterfrontmarathon.com/event-info/',label:'Official 2026 event information'},
 tokyo:{elevation:'Official elevation profile available',note:'The organizer publishes the full 2027 course map and elevation profile; a single cumulative-gain number is not stated.',source:'https://www.marathon.tokyo/en/about/course/',label:'Official 2027 course page'},
 marrakech:{elevation:'Flat and rapid; false-flat sections',note:'The organizer describes a flat, fast course with ascending false-flat sections through the palm grove.',source:'https://marrakechmarathon.com/race-info/',label:'Official race information'},
 berlin:{elevation:'Very flat; minor rise around 25–30 km',note:'World Athletics describes the course as fast while noting an uphill section between kilometres 25 and 30.',source:'https://worldathletics.org/waendurancemedicine/news/an-investigation-on-world-majors-marathons-running-performance-analysis-of-elite-runners',label:'World Athletics course analysis'},
};

export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const race=details[slug];if(!race)return{};const photo=cityCredits[slug as keyof typeof cityCredits];const image=`https://pace-atlas-marathons.khajan-y.chatgpt.site/images/cities/${photo.file}`;return{title:`${race.name} — Pace Atlas`,description:`${race.date}, registration, verified route information, pricing and transfer guidance for ${race.name}.`,openGraph:{title:`${race.name} — Pace Atlas`,description:`Plan ${race.name}: dates, course facts, entry details and policies.`,images:[image]},twitter:{card:'summary_large_image',title:`${race.name} — Pace Atlas`,description:`Plan ${race.name}: dates, course facts, entry details and policies.`,images:[image]}}}

export default async function RacePage({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const race=details[slug];if(!race)notFound();const photo=cityCredits[slug as keyof typeof cityCredits];const evidence=routeEvidence[slug]||{elevation:'Verified elevation total not published',note:'The organizer has not published a numeric cumulative-gain figure for the listed edition. The route summary is descriptive, not a measured elevation claim.',source:race.official,label:'Official organizer site'};return <main><section className="detail-hero"><img src={`/images/cities/${photo.file}`} alt={`${race.city} city view`}/><a className="photo-credit" href={photo.source} target="_blank" rel="noreferrer">City image: {photo.title} ↗</a><div className="shell detail-hero-content"><Link className="back-link" href="/#directory">← Back to all races</Link><div className="eyebrow"><span>●</span> {race.country} · Race guide</div><h1>{race.city}</h1><p>{race.name} · {race.distances}</p></div></section><section className="detail-main shell"><div className="fact-grid"><div className="fact"><span>Event date</span><strong>{race.date}</strong></div><div className="fact"><span>Registration</span><strong>{race.registration}</strong></div><div className="fact"><span>Course character</span><strong>{race.terrain}</strong></div><div className="fact"><span>Distances</span><strong>{race.distances}</strong></div><div className="fact"><span>Last verified</span><strong>October 5, 2026</strong><a href={race.official} target="_blank" rel="noreferrer">Official source</a></div></div><div className="detail-columns"><article><span className="kicker">THE COURSE</span><h2>Route & elevation</h2><p>{race.route}</p><div className="route-evidence"><span>ELEVATION EVIDENCE</span><strong>{evidence.elevation}</strong><p>{evidence.note}</p><a href={evidence.source} target="_blank" rel="noreferrer">{evidence.label} ↗</a></div><p>Courses can change between editions. Numerical elevation is shown only when a race organizer or governing body publishes it.</p></article><aside><div className="policy-card"><span>Ticket cost</span><strong>See official pricing</strong><p>Fees vary by residency, entry category, charity place, and registration phase. Taxes or processing charges may be additional.</p></div><div className="policy-card"><span>Transfer after purchase</span><strong>Restricted — verify policy</strong><p>Major races commonly prohibit informal bib transfers. Some organizers provide a controlled deferral or transfer window.</p><a className="official-button" href={race.official} target="_blank" rel="noreferrer">Check official race details ↗</a></div></aside></div></section></main>}
